### ISSUE TITLE
Implement raw-dylib for Windows

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustc_codegen_cranelift#1345]
This will require generating import libraries using the object crate. I don't know what the exact format of import libraries is, but I do know that MSVC and MinGW use an incompatible format.

**Comment by bjorn3** [comment]
Rust 1.71.0 released which stabilizes this feature, so it might become high priority to implement this in the near future if windows-sys switches to it.

**Comment by blyxyas** [comment]
I think I'll give this a try.

**Comment by bjorn3** [comment]
https://github.com/rust-lang/ar_archive_writer/pull/15 has ported LLVM's import library writer to rust. Using it from cg_clif produces identical import libraries as cg_llvm. It isn't enough however as we also need to match cg_llvm in when to use `__imp_` dllimport symbols, which we currently never use.

**Comment by bjorn3** [comment]
Implemented in https://github.com/rust-lang/rustc_codegen_cranelift/pull/1524.
