### ISSUE TITLE
cargo check fails for trust-dns-proto 0.22.0

### ISSUE THREAD

**Issue by teohhanhui** [rust-lang/rustc_codegen_cranelift#1401]
```
    Checking trust-dns-proto v0.22.0 (/home/teohhanhui/Projects/hickory-dns/hickory-dns/crates/proto)
error: missing optimized MIR for an item in the crate `tracing_core`
    |
note: missing optimized MIR for this item (was the crate `tracing_core` compiled with `--emit=metadata`?)
   --> /home/teohhanhui/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.29/src/callsite.rs:362:5
    |
362 |     fn set_interest(&self, interest: Interest) {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `trust-dns-proto` (lib) due to previous error
```

Seems like it's hitting this: https://github.com/rust-lang/rust/pull/115353

`cargo check -p trust-dns-proto` and `cargo +nightly check -p trust-dns-proto` are both successful.

**Comment by bjorn3** [comment]
Weird. I will see if I can reproduce this tomorrow.

**Comment by bjorn3** [comment]
Found the issue. cg_clif is calling `assert_module_sources` even when not doing codegen, which in turn triggers `collect_and_partition_mono_items` which will eventually fail with the error you are seeing. The LLVM backend only calls `assert_module_sources` when actually doing codegen.
