### ISSUE TITLE
_mm_packs_epi32 not implemented

### ISSUE THREAD

**Issue by bend-n** [rust-lang/rustc_codegen_cranelift#1413]
```rust
trap at Instance { def: Item(DefId(2:13710 ~ core[b9f2]::core_arch::x86::sse2::_mm_packs_epi32)), args: [] } (_ZN4core9core_arch3x864sse215_mm_packs_epi3217hba4b3ff5de2eb293E): llvm.x86.sse2.packssdw.128
```

to repro: clone [fimg](https://github.com/bend-n/fimg), run `cargo test nearest`.

**Comment by bend-n** [comment]
wait i just updated and i still hit this 🤔

**Comment by bjorn3** [comment]
The fix has landed in this repo, but I haven't synced it to the rust repo yet, so it isn't available on nightly right now. I will let you know when it lands on nightly.

**Comment by bjorn3** [comment]
The fix has landed on nightly now.
