### ISSUE TITLE
Unimplemented x86 llvm intrinsic pcmpestrm128

### ISSUE THREAD

**Issue by pothos** [rust-lang/rustc_codegen_cranelift#1418]
When compiling `hard-xml` I noticed two warnings for a missing x86 llvm intrinsic `pcmpestrm128`:
```
warning: unsupported x86 llvm intrinsic llvm.x86.sse42.pcmpestri128; replacing with trap
```

Edit: And of course a huge **thank you** for your work and congratulations for getting it into rustup!

**Comment by bjorn3** [comment]
That is quite a complex intrinsic: https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_cmpestri&ig_expand=939 I don't think I will get around implementing it in the next couple of days.

> And of course a huge thank you for your work and congratulations for getting it into rustup!

:heart:

**Comment by bjorn3** [comment]
Implemented this using inline asm to directly call the original instruction over at https://github.com/rust-lang/rustc_codegen_cranelift/tree/more_simd_intrinsics

**Comment by pothos** [comment]
Thanks a lot, tested it and it works :)

**Comment by bjorn3** [comment]
A fix is available on the latest nightly.

**Comment by bjorn3** [comment]
So far I have been implementing new vendor intrinsics as people report them actually being used. There are a lot of them that basically nobody uses. Unless I know of a user to test it with, it is hard for me to be confident that I correctly implemented a intrinsic. If you find other unimplemented intrinsics that some program or library needs, please do let me know.
