### ISSUE TITLE
Is "parallel-rustc" already usable with cg_clif?

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/rustc_codegen_cranelift#1423]
Just a simple question out of curiosity.

Is https://blog.rust-lang.org/2023/11/09/parallel-rustc.html already usable with cg_clif?

**Comment by bjorn3** [comment]
Most of this happens before involvement of the codegen backend. This part should works just fine. The LLVM backend also does translation from MIR to LLVM ir in parallel. cg_clif doesn't yet do the translation from MIR to clif ir in parallel.

**Comment by bjorn3** [comment]
Opened https://github.com/rust-lang/rustc_codegen_cranelift/pull/1489 to implement this.
