### ISSUE TITLE
panic at  llvm.x86.sha256rnds2

### ISSUE THREAD

**Issue by numfin** [rust-lang/rustc_codegen_cranelift#1427]
idk much about it, but i hope it helps to track issue

error is:

```
trap at Instance { def: Item(DefId(1:15069 ~ core[8f41]::core_arch::x86::sha::_mm_sha256rnds2_epu32)), args: [] } (_ZN4core9core_arch3x863sha21_mm_sha256rnds2_epu3217h44fb38c4b68babe8E): llvm.x86.sha256rnds2
```

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rustc_codegen_cranelift/pull/1425 should have fixed this. It isn't available on rustup yet. You could download from https://github.com/rust-lang/rustc_codegen_cranelift/releases/tag/dev though.

**Comment by bjorn3** [comment]
Should be fixed with today's nightly.

**Comment by numfin** [comment]
@bjorn3 confirm - fixed
