### ISSUE TITLE
Noting platform support in README

### ISSUE THREAD

**Issue by jollygreenlaser** [rust-lang/rustc_codegen_cranelift#1441]
```
If your project doesn't use any of the things listed under "Not yet supported", it should work fine. If not please open an issue.
```

M1/M2 macs are not supported. It's actually kind of unclear which platforms are supported, if any, beyond the `Linux and x86_64 macOS` that are noted as having nightly binaries. 

It would be nice to have platform support explicitly noted so users can determine whether to attempt an install. 

Related: #1248

**Comment by bjorn3** [comment]
Done

**Comment by jollygreenlaser** [comment]
Beautiful thank you!
