### ISSUE TITLE
trap at Instance `x86::sse::_mm_prefetch`

### ISSUE THREAD

**Issue by luxalpa** [rust-lang/rustc_codegen_cranelift#1448]
I'm getting this error (on Windows):

```
trap at Instance { def: Item(DefId(2:13956 ~ core[ba5e]::core_arch::x86::sse::_mm_prefetch)), args: [3_i32] } (_ZN4
core9core_arch3x863sse12_mm_prefetch17h8b14a40b0b8e680cE): llvm.prefetch
```

Not entirely sure what it means. Missing intrinsic maybe?

**Comment by bjorn3** [comment]
Could you try the llvm-prefetch branch? Github actions is having an outage right now, so I unfortunately can't provide a prebuilt version until the outage is solved.

**Comment by luxalpa** [comment]
Thanks, I tried the branch, it works perfectly! 🐉

**Comment by bjorn3** [comment]
Merged https://github.com/rust-lang/rustc_codegen_cranelift/commit/0dc13d7acb0118d6c14a9209d921e5278e829458.
