### ISSUE TITLE
.debug_str wrong

### ISSUE THREAD

**Issue by limuy2022** [rust-lang/rustc_codegen_cranelift#1496]
I have reported it to the author of mold before.[there](https://github.com/rui314/mold/issues/1240) are the details.(Without cranelift the warning and error will disappear so I report this here)

**Comment by philipc** [comment]
https://github.com/gimli-rs/object/pull/694 is the first step to fixing this.

**Comment by bjorn3** [comment]
Should be fixed now on the master branch. Will sync it to the rust repo later.

**Comment by philipc** [comment]
`.debug_line_str` needs it too.

**Comment by bjorn3** [comment]
Fixed in 126fd7c3.
