### ISSUE TITLE
will it compatible with mold?

### ISSUE THREAD

**Issue by Mon-ius** [rust-lang/rustc_codegen_cranelift#1498]
Can I use such config in https://github.com/benwis/customs/issues/1

**Comment by bjorn3** [comment]
It works with mold. There is currently a minor issue where the combination of cg_clif + mold + valgrind doesn't work (https://github.com/rust-lang/rustc_codegen_cranelift/issues/1496), but other than that there should be no problems.

**Comment by Mon-ius** [comment]
Indeed, I met a similar error when introduced `ffmpeg-next = { version = "7.0.2", features=["build"] }` on the `dependencies`, says, 

`warning: LTO is not supported. You may get a linker error.`

**Comment by bjorn3** [comment]
cg_clif doesn't support LTO. You need to disable it in your Cargo.toml or wherever you enabled it.

**Comment by Mon-ius** [comment]
will it support `LTO` in future?

**Comment by bjorn3** [comment]
It may support the LTO commandline option in the future, but is unlikely to see any runtime performance benefit from it. Cranelift doesn't do any inlining or other inter-procedural optimizations, which are the main reason for having LTO at all.

**Comment by bjorn3** [comment]
Closing as there is no bug/feature this is tracking, but feel free to ask more questions if you have them.
