### ISSUE TITLE
`panic in a function that cannot unwind` anytime a thread panics

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/rustc_codegen_cranelift#1499]
Running `thread::spawn(|| panic!("wat"));` is enough to cause a whole program abort which is unfortunate.

**Comment by bjorn3** [comment]
Cranelift doesn't yet support unwinding, so any panic will always abort.

**Comment by SUPERCILEX** [comment]
Ohhhh, ok that makes sense. Thanks!
