### ISSUE TITLE
rustc-codegen-cranelift-preview support for aarch64-apple-darwin

### ISSUE THREAD

**Issue by yerke** [rust-lang/rustc_codegen_cranelift#1502]
After the recent announcement for fixes for Apple Silicon I tried to install rustc-codegen-cranelift-preview component by following the instructions in the readme, but got an error.

```
> rustup component add rustc-codegen-cranelift-preview --toolchain nightly
error: component 'rustc-codegen-cranelift' for target 'aarch64-apple-darwin' is unavailable for download for channel 'nightly'
Sometimes not all components are available in any given nightly.
```

Am I doing something wrong or is the current nightly channel currently missing something? I have nightly-aarch64-apple-darwin (3cb521a43 2024-06-22).

Edit: Oh, I just saw that the footnote still applies: `Not available as rustup component for nightly. You can build it yourself.`.

I guess my question now is the following: is there anything preventing adding rustc-codegen-cranelift-preview rustup component for aarch64-apple-darwin?

Thanks!

**Comment by bjorn3** [comment]
I would prefer to see https://github.com/bytecodealliance/wasmtime/issues/8730 fixed first. Without it you need to switch back to the old linker on arm64 macOS if you use XCode 15 or later.

**Comment by yerke** [comment]
Got it. `RUSTFLAGS="-Clink-arg=-ld_classic"` worked for me.

**Comment by bjorn3** [comment]
https://github.com/bytecodealliance/wasmtime/issues/8730 has been fixed. Opened a subtree sync PR and will open a PR to distribute cg_clif as rustup component for arm64 macOS once it merges.
