### ISSUE TITLE
Dynamically linked library path resolution with `cargo clif test --doc` differs from `cargo test --doc`

### ISSUE THREAD

**Issue by janhohenheim** [rust-lang/rustc_codegen_cranelift#1505]
In https://github.com/bevyengine/bevy/issues/14129, we discovered an issue when running `cargo test --doc` on Windows when linking Bevy dynamically. See that issue for a reproducible minimal example.

In https://github.com/bevyengine/bevy-website/pull/1522, I added a workaround to Bevy's documentation, namely:
> In order to run `cargo test --doc`, you must also add the path returned by `rustc --print target-libdir` to your `PATH` environment variable.

This fixes this issue when running `cargo test --doc`, but `cargo clif test --doc` still results in a dynamic library resolution error:
```
Test executable failed (exit code: 0xc0000135).
```

**Comment by bjorn3** [comment]
cargo-clif uses a separate sysroot. I think you can use `rustc-clif --print target-libdir` where rustc-clif is the executable right next to the cargo-clif you used for running tests.

**Comment by janhohenheim** [comment]
I've added the output of that command to my `PATH` and tried running doc tests in a project I happened to have open. One that previously failed now runs, which is good, however the other two fail with the following:
```
Test executable failed (exit code: 0xc000001d).

stderr:
thread 'main' panicked at D:\a\rustc_codegen_cranelift\rustc_codegen_cranelift\build\stdlib\library\std\src\sync\once.rs:217:20:
assertion failed: state_and_queue.addr() & STATE_MASK == RUNNING
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'll try seeing if this also happens on the linked minimal example.

**Comment by janhohenheim** [comment]
I did not manage to get the exact error message, but another one. Opening a new issue since this one is resolved at least.
