### ISSUE TITLE
Little questions to help

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/rustc_codegen_cranelift#1506]
Hi @bjorn3,

thanks as always for your AMAZING AMAZING AMAZING work!

Is there a way to know how much work is missing from this project to be considered stable?

What can he do - who knows how - to help you finish?

How can you "split" the remaining work into tasks?

**Comment by bjorn3** [comment]
Apart from unwinding support and full std::arch support (which I'm both working on) there are not really major things that are missing. Just a lot of small bugs and papercuts. Better debuginfo support is a nice to have, but not essential. Currently the biggest bugs are the bevy issues opened today as well as a couple of bugs reported by the new abi-cafe version for which I still need to open an issue.

**Comment by frederikhors** [comment]
So - to better understand - what separates us from a stable release are the 71 issues minus this? Or even less?

Can we create a [milestone](https://github.com/rust-lang/rustc_codegen_cranelift/milestones)?

**Comment by frederikhors** [comment]
Ok. How can we make clear these points? Milestones with only a few issues written (and updated in the future) by you like in this issue?

**Comment by frederikhors** [comment]
I cannot create milestones unfortunately.
