### ISSUE TITLE
Can I make it build the build script with LLVM, but the main projech with Cranelift?

### ISSUE THREAD

**Issue by vi** [rust-lang/rustc_codegen_cranelift#1529]
How do I take advantage of cranelift codegen speedup in a project that uses lalrpop in a build script?

When a project (e.g. [Nickel](https://github.com/tweag/nickel)) has a lalrpop in build script, the build script should be build with optimisations even when other parts are built for debugging.

This is possible with Cargo profile overrides and results in a reasonable debug build time.

However, when I use cg_clif mode I get compilation stuck in running the build script even with profile overrides.

Can I switch Cranelift mode off for build script, just like the optimisation level in overridden profile?

**Comment by bjorn3** [comment]
```toml
[profile.dev.build-override]
codegen-backend = "llvm"
```

should work if you use cg_clif from rustup.
