### ISSUE TITLE
Is there a way to use `cargo-clif clippy` in VSCode too?

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/rustc_codegen_cranelift#1539]
I'm using cranelift for a while now.

I'm using VSCode too and these settings:

```json
"rust-analyzer.checkOnSave": true,
"rust-analyzer.runnables.extraEnv": {
    "RUST_BACKTRACE": "0"
},
"rust-analyzer.cargo.extraArgs": [
    "--target-dir",
    "target/rls/"
],
"rust-analyzer.check.command": "clippy",
```

I'm wondering if there is a way to speed-up the "cargo-clif clippy" too directly in VSCode.

What do you think?

**Comment by bjorn3** [comment]
Clippy is effectively doing a check build, skipping codegen entirely. As such the only case where you would benefit from using cg_clif with clippy is if you are changing build scripts, proc macros or their dependencies as those are the only things for which codegen actually happens in a check build.
