### ISSUE TITLE
Is it possible to develop on new Apple Silicon CPUs?

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/rustc_codegen_cranelift#1543]
Since I'm planning to buy a new Macbook Pro M4 and since this project is the coolest thing in the Rust world, I would like to understand if I can use cranelift for the development build (debug) as I do on Linux and Windows today.

I already thought so, but I got the doubt from here: https://www.reddit.com/r/rust/comments/1gnxqu1/comment/lwjn0ze/.

Thanks for all you do!

**Comment by bjorn3** [comment]
It should work just fine. In the past there were a bunch of (now fixed) issues that made it unusable, so I can understand the confusion. For the time being I would recommend you to use the precompiled version from https://github.com/rust-lang/rustc_codegen_cranelift/releases/tag/dev or build it from source yourself though. There is still a couple of ABI issues that show up when mixing LLVM and Cranelift compiled libraries as would happen with the rustup version (the standard library there is always LLVM compiled) The tracking issue for these ABI issues is https://github.com/rust-lang/rustc_codegen_cranelift/issues/1525.
