### ISSUE TITLE
info message on each command

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/rustc_codegen_cranelift#1549]
I'm trying the latest dev version (https://github.com/rust-lang/rustc_codegen_cranelift/commit/3ebaf047071afae07229ff8fb5e05527fa6d9645) right now and on each command I get this in command line:

```
info: syncing channel updates for 'nightly-2024-12-11-x86_64-pc-windows-msvc'
info: latest update on 2024-12-11, rust version 1.85.0-nightly (33c245b9e 2024-12-10)
```

Is this a bug?

**Comment by bjorn3** [comment]
That shouldn't happen. Do you know roughly what the last known working version was?

**Comment by frederikhors** [comment]
This one was the last one I was using without issues: cargo 1.84.0-nightly (66221abde 2024-11-19).

**Comment by frederikhors** [comment]
Oh wow. I simply changed the files from that version to the current one. Nothing else.

**Comment by frederikhors** [comment]
Can it be an issue with rust 1.85 nightly?

**Comment by bjorn3** [comment]
I tested with the latest available version on CI, which uses `rustc 1.85.0-nightly (33c245b9e 2024-12-10)` too.

**Comment by frederikhors** [comment]
On Windows?

**Comment by bjorn3** [comment]
No, not on Windows. I can't easily test on Windows though. I could try to ask if someone else can reproduce this issue.

**Comment by jieyouxu** [comment]
FWIW, I'm on `x86_64-pc-windows-msvc`, latest cg_clif checkout at 53bbef83, I am unable to reproduce the `info:` messages. Default cargo configuration, no specific cg_clif config at all.

Example output:

```
PS X:\repos\rustc_codegen_cranelift> .\dist\cargo-clif.exe --version
cargo 1.85.0-nightly (769f622e1 2024-12-14)
```

**Comment by jieyouxu** [comment]
When I explicitly remove all nightly toolchains, I observe:

```
PS X:\repos\rustc_codegen_cranelift> ./y.ps1 prepare
[BUILD] build system
info: syncing channel updates for 'nightly-2024-12-18-x86_64-pc-windows-msvc'
info: latest update on 2024-12-18, rust version 1.85.0-nightly (a4cb3c831 2024-12-17)
```

However, at least for me, this only happens once -- when rustup has to fetch the nightly toolchain for the first time.

```
PS X:\repos\rustc_codegen_cranelift> .\dist\cargo-clif.exe --version
cargo 1.85.0-nightly (769f622e1 2024-12-14)
```

**Comment by frederikhors** [comment]
I'm on https://github.com/rust-lang/rustc_codegen_cranelift/commit/da415e17c80cd2d79c50ceb66148fa9a4561321c right now and it works.
